### ISSUE TITLE
Aries Xamarin isn't compatible with Android API 30

### ISSUE THREAD

**Issue by x0axz** [hyperledger/aries-mobile-agent-xamarin#52]
Hi,

I'm trying to upload my app to Google Play Store, but it isn't allowing me to publish it.

```
Your app currently targets API level 29 and must target at least API level 30 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 30. 
```

When I tried to upgrade the API level to 30, I'm keep getting an IO error while trying to create a pool.  On Android 30 can't create a pool, however with Android 29, it works fine.

**AndroidManifest.xml**

```
<uses-sdk android:minSdkVersion="26" android:targetSdkVersion="30" />

<application android:requestLegacyExternalStorage="true" android:allowBackup="false" android:fullBackupOnly="false"></application>

<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Error Logs**

```
9/28/2021 5:59:16 PM - Couldn't create pool config: Hyperledger.Indy.IOException: An IO error occurred. at Hyperledger.Aries.Ledger.DefaultPoolService.Crea tePoolAsync (System.String poolName, System.String genesisFile) [0x00072] in :0 at Osma.Mobile.App. Services.PoolConfigurator.ConfigurePoolsAsync() [0x0023c] in :0

9/28/2021 5:59:16 PM - Couldn't create pool config: Hyperledger.Indy.IOException: An IO error occurred. at Hyperledger.Aries.Ledger.DefaultPoolService.Crea tePoolAsync (System.String poolName, System.String genesis File) [0x00072] in :0 at Osma.Mobile.App.

Services.PoolConfigurator.Configure PoolsAsync()

[0x0023c] in :0

9/28/2021 5:59:16 PM - Couldn't create pool config: Hyperledger.Indy.IOException: An IO error occurred. at Hyperledger.Aries.Ledger.Default PoolService.Crea tePoolAsync (System.String poolName, System.String genesisFile) [0x00072] in :0 at Osma.Mobile.App. Services.PoolConfigurator.Configure PoolsAsync()
```

**Comment by x0axz** [comment]
Resolved it.

Starting in Android 11, apps cannot create their own app-specific directory on external storage. To access the directory that the system provides for your app, call `getExternalFilesDirs()`.

**getExternalFilesDirs**
https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String)

To get private ExternalStorage you can use this

`Android.App.Application.Context.GetExternalFilesDir(null).AbsolutePath;`

So, in `Services/PoolConfigurator.cs`, change

`Path.Combine(FileSystem.CacheDirectory, config.Value);`

to

`Path.Combine(Android.App.Application.Context.GetExternalFilesDir(FileSystem.CacheDirectory).AbsolutePath, config.Value);`

**Comment by x0axz** [comment]
Have a look into this Issue, it'll be helpful: https://github.com/hyperledger/aries-mobile-agent-xamarin/issues/53.

**Comment by leonx99x** [comment]
`
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" android:versionCode="1" android:versionName="0.1.0" package="com.ariesmax" android:installLocation="internalOnly">
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29" />
	<application android:label="AriesMax" android:allowBackup="false" android:fullBackupOnly="false"></application>
	<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" tools:node="remove" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
	<uses-permission android:name="android.permission.CAMERA" />
</manifest>
`

It was like above and I removed "tools:node="remove"" parts. After that I changed Android MainActivity.cd like this:

`
 readonly string[] _permissionsRequired =
        {
            Manifest.Permission.Camera,
            Manifest.Permission.ReadExternalStorage,
            Manifest.Permission.WriteExternalStorage
        };

`
It now asks permission for storage too. But still is stacked at creating wallet screen.
